### PR TITLE
Correct regular expressions for amount

### PR DESCRIPTION
**Pull request by mt-clearhaus**
Fixes https://github.com/clearhaus/gateway-api-docs/issues/143.

### CODE REVIEW

**Review by ct-clearhaus — APPROVED** [review]
👍

**Comment by misozask** [comment]
Are you sure that `(0|[1-9][0-9]{,8})` is correct regex?
I assume it should rather be `^(0|[1-9][0-9]{0,8})$`

**Comment by mt-clearhaus** [comment]
`^` and `$` are implied in the regexes mentioned in the documentation. It is optional but valid to leave out `0` in a quantifier.

**Comment by misozask** [comment]
`{,8}` is valid? Doesn't look like as 
> {,8} matches the characters {,8} literally (case sensitive)
 https://regex101.com/r/GV0qpX/1

**Comment by misozask** [comment]
> ^ and $ are implied in the regexes mentioned in the documentation

Somehow I can't find it ...

**Comment by mt-clearhaus** [comment]
For most applications if you ask them to expect Extended Regular Expressions (EREs), opposed to Basic Regular Expressions (BREs), they will interpret `{a,b}` as a quantifier, not as the five literal characters. Many applications accept `a` or `b` being left out. With `a` left out this means "the preceding element or subexpression must occur at most `b` times.", i.e. no lower bound. With `b` left out this means "the preceding element or subexpression must occur at least `a` times.", i.e. no upper bound. It appears various applications and help sites do not fully agree on a strict distinction between BRE and ERE and whether or not bounds may be left out. There does not appear to be any widespread consensus.

The expressions used in our documention are deliberately intended to be understood by a human rather than an application. We also employ home-made expressions, e.g. `[:UUIDv4:]` for `series[previous][id]`. This is also why we do not think it is necessary to include `^` and `$` in all expressions—or mention explicitly that we have made that choice.

**Comment by misozask** [comment]
Yes, I've figured out that some regex flavors supports also `{,b}`. But IMHO most common ones does not.
https://www.regular-expressions.info/refrepeat.html

So, up to you if you want to make your clients wonder about it (when they blindly copy it, as I did), or rather use syntax recognized in all flavors ...
Just my two cents ...

Thanks anyway!

**Pull request merged**
