### PR TITLE
Explain CSC to be supplied when available

### PR DESCRIPTION
**Pull request by ct-clearhaus**

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
RFR @mt-clearhaus

**Comment by soltveit** [comment]
Deployed, but I just noticed a little CSS thingy that needs to be fixed.

**Comment by ct-clearhaus** [comment]
Argh, the backticks aren't working within HTML :disappointed:

**Comment by soltveit** [comment]
Fixed it last night.

**Comment by ct-clearhaus** [comment]
https://github.com/clearhaus/gateway-api-docs/commit/adb083c5d0966cbf427b5eb60cb13310daf97c28

:+1:

**Pull request merged**
