### PR TITLE
Add invalid transaction status code

### PR DESCRIPTION
**Pull request by ct-clearhaus**
This error code will be used for transactions that are not possible.

For instance a subsequent recurring transaction for a Maestro card where the merchant has not been assigned a static AAV.

A detailed and descriptive `status.message` should be returned explaining the specific issue.

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
@mt-clearhaus @soltveit By the way, does the numbering make sense? (AKA "Invitation to bikeshed" 😛) Take https://github.com/clearhaus/gateway-api-docs/pull/41 into account.

**Comment by soltveit** [comment]
We have e.g. these that relate to card expiry:

```
40130	Invalid expire date
40135	Card expired
```

Perhaps have a 401x0 number for both  `Invalid transaction` and `Invalid text on statement`.

**Comment by ct-clearhaus** [comment]
And "invalid transaction" will likely be the "last resort" ... so `40190`?

**Comment by mt-clearhaus** [comment]
Deployed in production today in the timespan 15:15-16:00 CEST.

**Comment by ct-clearhaus** [comment]
Resolved the merge conflict 🙂

**Pull request merged**
