### PR TITLE
Add STN/930 and MRU/929 currencies

### PR DESCRIPTION
**Pull request by ad-clearhaus**
See https://github.com/clearhaus/issues-pci/issues/517 for discussion.

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
Maybe comment somewhere when STN is available?

**Comment by ad-clearhaus** [comment]
Added note to `index.md`. Any objections?

**Comment by mt-clearhaus** [comment]
I am not sure I understand "currency x is running with currency y", but that might just be me.

Suggestion:

```
### MRU/929 and STN/930 support

Starting 2018-xx-xxTxx:xx:xx+00:00 we support the currencies MRU/929 and STN/930.

### STD/678 no longer accepted from July, 2018

Starting 2018-07-01T00:00:00+00:00 the currency STD/678 is no longer accepted.
```

(the text from OmniPay is "will no longer be allowed for card transactions after 30 June 2018")

Sorry for being an obnoxious donkey's behind.

**Comment by ad-clearhaus** [comment]
More to the point. :+1:

**Comment by mt-clearhaus** [comment]
@ad-clearhaus :eyes:

**Comment by ad-clearhaus** [comment]
I don't have any strong feelings about keeping the numeric version. :) In any case :+1: The wording in better.

**Comment by mt-clearhaus** [comment]
@soltveit Will you publish this?

**Comment by soltveit** [comment]
Deployed.

**Pull request merged**
