### PR TITLE
Sensible length requirements

### PR DESCRIPTION
**Pull request by ct-clearhaus**
* Require text_on_statement to have at least 2 characters if present.
* Require reference to have at least 1 character if present.
* Remove a few trailing spaces.

### CODE REVIEW

**Comment by ct-clearhaus** [comment]
> I see no empty strings as reference in the last 31 days.

We need to see in the request params due to https://github.com/clearhaus/klovedal/blob/master/lib/klovedal/filter/format/text_on_statement.rb#L8

**Comment by mt-clearhaus** [comment]
Of course. You are right. We currently fall back from empty string to `nil`. Clients utilizing this fallback will have to change their behaviour, and then we can start enforcing the more restrictive regex.

**Comment by mt-clearhaus** [comment]
56,191 requests with `"text_on_statement"=>""` in the last 14 days, distributed on 106 API keys:

```
START=$(date -d '14 days ago' +%s)000
FILTER='/Klovedal::ApiKey.*"text_on_statement"=>""/'
ENCODED_FILTER=`echo $FILTER | ruby -e 'require "cgi"; puts CGI.escape gets.chomp'`
curl -s "https://pull.logentries.com/$ACCOUNT_KEY/hosts/clrhs-prod-pci-procesr/gateway/?start=$START&filter=$ENCODED_FILTER" > tos.log

wc -l tos.log 
56191 tos.log

egrep -o 'Klovedal::ApiKey \([0-9a-f-]{36}\)' tos.log | egrep -o '[0-9a-f-]{36}' | sort | uniq | wc -l
106
```

Affected merchants: [top-empty-string-tos-14-days.txt](https://github.com/clearhaus/gateway-api-docs/files/1351779/top-empty-string-tos-14-days.txt)

**Comment by mt-clearhaus** [comment]
I have updated the earlier-posted list with PSPs:

[top-empty-string-tos-14-days.txt.gpg.gz](https://github.com/clearhaus/gateway-api-docs/files/1355663/top-empty-string-tos-14-days.txt.gpg.gz)

**Comment by ct-clearhaus** [comment]
Already fixed.

**Pull request closed without merging**
